substitutions:
  device_description: "Monitor and control a Seplos V3 BMS multipack"
  name: seplos
  friendly_name: "Seplos Polo W multi pack"
  tx_pin: GPIO43
  rx_pin: GPIO44
  delta: "5" # update interval for all data points

external_components:
  - source:
      type: git
      url: https://github.com/Hevak/seplos_v3_sniffer
    refresh: 1min
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: arduino
    version: latest

ota:
  - platform: esphome

web_server:
  port: 80
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 1min
  manual_ip:
    static_ip: 192.168.188.186
    gateway: 192.168.188.1
    subnet: 255.255.255.0

logger:
  level: INFO
  baud_rate: 0

api:

uart:
  id: uart_0
  baud_rate: 19200
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  # The increased RX buffer size is important because
  # the full BMS response must fit into the buffer
  rx_buffer_size: 384

seplos_parser:
  id: seplos_v3
  bms_count: 2  # Anzahl der Akku's (max. 16)
  update_interval: ${delta}
  uart_id: uart_0  # SeplosParser verwendet diese UART ID

packages:
  sensors_bms0: !include 
    file: "seplos/seplos_mono_sensor.yaml"
    vars:
      bms: bms0
      delta: ${delta}
  sensors_bms1: !include
    file: "seplos/seplos_mono_sensor.yaml"
    vars:
      bms: bms1
      delta: ${delta}
  text_sensors_bms0: !include 
    file: "seplos/seplos_mono_text_sensor.yaml"
    vars:
      bms: bms0
  text_sensors_bms1: !include
    file: "seplos/seplos_mono_text_sensor.yaml"
    vars:
      bms: bms1
